### ISSUE TITLE
0.592kN Dual Radial Engine no plume on Cavea-B

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/ROEngines#23]
Not sure yet if this is only this engine, or all of ROEngines/PartConfigs/PLE_NicheParts.

**Comment by gazpachian** [comment]
I've been having the same issues in my install where some configs have working plumes and others don't for these niche parts. I built a test rig in a sandbox save to confirm that at least illustrates parts of the issue. All engines are using TL 2 configs and I've verified that smokescreen is not generating particles for the engines with invisible plumes rather than there being some weird offset issue or missing texture:
![realplumes](https://user-images.githubusercontent.com/3220774/62418156-b79c4480-b663-11e9-82d0-d56396807a93.png)

Furthermore, as can just barely be seen in the screenshot above, the plumes are not necessarily offset by the right amount in the cases they do work. Below is a similar setup in orbit with just the HTP configured thruster block and some scaffolding to further show the individual plume offsets as they are right now:

![plumeoffset](https://user-images.githubusercontent.com/3220774/62418252-3d6cbf80-b665-11e9-97e7-a42b87c5469a.png)

The plume configs likely need to be split on a per engine basis to fix the offsets, that's the easy part and I can volunteer to do so. Why applying certain fuel configs to engines disable the plumes is however beyond my understanding of the RO patch structure so I'll leave that for someone else to discover for now. :)

**Comment by gazpachian** [comment]
@Gordon-Dry I got both issues solved and did so with less hassle than I thought it would be. Try out the configs from my 'plumes' branch and see if they work for you as well! =)

**Comment by Gordon-Dry** [comment]
I will do, thanks for the effort.

**Comment by Capkirk123** [comment]
Should have been fixed here: https://github.com/KSP-RO/ROEngines/pull/39
